spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: devpet0327@gmail.com
    password: lavf fhcw izcy ksjp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
